// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoMidasAPI.Data;

#nullable disable

namespace ProjetoMidasAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106194230_AddEmprestimos")]
    partial class AddEmprestimos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Emprestimo", b =>
                {
                    b.Property<int>("IdSimEmprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSimEmprestimo"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacaoSE")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IOFemprestimo")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("descricaoEmprestimo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("despesasEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nomeEmprestimo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("parcelasEmprestimo")
                        .HasColumnType("int");

                    b.Property<string>("provedorEmprestimo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tarifasEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorParcelas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdSimEmprestimo");

                    b.ToTable("Emprestimos", (string)null);
                });

            modelBuilder.Entity("Lancamento", b =>
                {
                    b.Property<int>("IdLancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLancamento"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoLancamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdProjecao")
                        .HasColumnType("int");

                    b.Property<string>("ObservacaoLancamento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("idRecorrente")
                        .HasColumnType("int");

                    b.HasKey("IdLancamento");

                    b.ToTable("Lancamentos", (string)null);
                });

            modelBuilder.Entity("ProjetoMidasAPI.Models.Projecao", b =>
                {
                    b.Property<int>("IdProjecao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProjecao"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProjecao");

                    b.ToTable("Projecoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
