// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoMidasAPI.Data;

#nullable disable

namespace ProjetoMidasAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112023829_AjusteUsuarioLancamento")]
    partial class AjusteUsuarioLancamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("cnpjEmpresa")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("emailEmpresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("idResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("nomeFantasia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("telefoneEmp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresas", (string)null);

                    b.HasData(
                        new
                        {
                            IdEmpresa = 1,
                            cnpjEmpresa = "12345678901234",
                            emailEmpresa = "empresa@teste.com",
                            idResponsavel = 1,
                            nomeFantasia = "Teste",
                            razaoSocial = "Empresa Teste",
                            telefoneEmp = "123456789"
                        });
                });

            modelBuilder.Entity("Emprestimo", b =>
                {
                    b.Property<int>("IdSimEmprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSimEmprestimo"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacaoSE")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IOFemprestimo")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("descricaoEmprestimo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("despesasEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nomeEmprestimo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("parcelasEmprestimo")
                        .HasColumnType("int");

                    b.Property<string>("provedorEmprestimo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tarifasEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorParcelas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdSimEmprestimo");

                    b.ToTable("Emprestimos", (string)null);
                });

            modelBuilder.Entity("Lancamento", b =>
                {
                    b.Property<int>("IdLancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLancamento"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoLancamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdProjecao")
                        .HasColumnType("int");

                    b.Property<int?>("IdSimEmprestimo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ObservacaoLancamento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("idRecorrente")
                        .HasColumnType("int");

                    b.HasKey("IdLancamento");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Lancamentos", (string)null);
                });

            modelBuilder.Entity("ProjetoMidasAPI.Models.Projecao", b =>
                {
                    b.Property<int>("IdProjecao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProjecao"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProjecao");

                    b.ToTable("Projecoes", (string)null);
                });

            modelBuilder.Entity("Recorrencia", b =>
                {
                    b.Property<int>("idRecorrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRecorrente"));

                    b.Property<int?>("IdProjecao")
                        .HasColumnType("int");

                    b.Property<int?>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<int>("TipoRecorrenciaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("dsRecorrente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("momentoCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("obRecorrente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("qtdeRecorrente")
                        .HasColumnType("int");

                    b.HasKey("idRecorrente");

                    b.HasIndex("TipoRecorrenciaId");

                    b.ToTable("Recorrencias", (string)null);
                });

            modelBuilder.Entity("Responsavel", b =>
                {
                    b.Property<int>("IdResponsavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResponsavel"));

                    b.Property<string>("emailResponsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("sobrenomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("telefoneResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdResponsavel");

                    b.ToTable("Responsaveis", (string)null);

                    b.HasData(
                        new
                        {
                            IdResponsavel = 1,
                            emailResponsavel = "joao.silva@teste.com",
                            nomeResponsavel = "João",
                            sobrenomeResponsavel = "Silva",
                            telefoneResponsavel = "987654321"
                        });
                });

            modelBuilder.Entity("TipoRecorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PadraoSistema")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TipoRecorrencias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Mensal",
                            PadraoSistema = true
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Semanal",
                            PadraoSistema = true
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Anual",
                            PadraoSistema = true
                        });
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Visitante");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("emailUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sobrenome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            IdEmpresa = 0,
                            PasswordHash = new byte[] { 82, 90, 131, 3, 89, 155, 201, 21, 77, 29, 246, 119, 20, 35, 222, 84, 233, 99, 208, 245, 43, 114, 249, 245, 253, 251, 231, 196, 200, 13, 200, 63, 102, 31, 104, 233, 62, 30, 170, 182, 199, 238, 186, 14, 48, 141, 229, 129, 224, 128, 39, 233, 78, 147, 244, 235, 1, 208, 142, 231, 102, 35, 236, 72 },
                            PasswordSalt = new byte[] { 59, 165, 164, 215, 142, 78, 162, 224, 209, 239, 127, 72, 79, 109, 70, 165, 191, 241, 26, 196, 131, 84, 223, 217, 54, 38, 16, 21, 243, 85, 109, 77, 28, 34, 214, 251, 51, 173, 96, 68, 194, 140, 229, 17, 239, 137, 38, 180, 9, 13, 43, 16, 36, 41, 5, 82, 158, 132, 92, 18, 10, 95, 169, 198, 225, 205, 188, 234, 171, 5, 43, 149, 170, 165, 184, 111, 17, 203, 5, 92, 170, 240, 132, 185, 10, 198, 167, 149, 83, 41, 58, 33, 136, 31, 188, 154, 96, 232, 62, 192, 163, 41, 77, 14, 221, 131, 111, 68, 26, 144, 15, 196, 123, 206, 92, 109, 160, 163, 228, 49, 124, 227, 188, 10, 119, 124, 99, 25 },
                            Perfil = "Administrador",
                            TipoUsuario = 7,
                            emailUsuario = "",
                            nome = "",
                            nomeUsuario = "Admin",
                            sobrenome = "",
                            telefone = ""
                        });
                });

            modelBuilder.Entity("Lancamento", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Lancamentos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Recorrencia", b =>
                {
                    b.HasOne("TipoRecorrencia", "TipoRecorrencia")
                        .WithMany()
                        .HasForeignKey("TipoRecorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoRecorrencia");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
