// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoMidasAPI.Data;

#nullable disable

namespace ProjetoMidasAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112024454_Ajusto")]
    partial class Ajusto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("cnpjEmpresa")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("emailEmpresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("idResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("nomeFantasia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("telefoneEmp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresas", (string)null);

                    b.HasData(
                        new
                        {
                            IdEmpresa = 1,
                            cnpjEmpresa = "12345678901234",
                            emailEmpresa = "empresa@teste.com",
                            idResponsavel = 1,
                            nomeFantasia = "Teste",
                            razaoSocial = "Empresa Teste",
                            telefoneEmp = "123456789"
                        });
                });

            modelBuilder.Entity("Emprestimo", b =>
                {
                    b.Property<int>("IdSimEmprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSimEmprestimo"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacaoSE")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IOFemprestimo")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("descricaoEmprestimo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("despesasEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nomeEmprestimo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("parcelasEmprestimo")
                        .HasColumnType("int");

                    b.Property<string>("provedorEmprestimo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tarifasEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorParcelas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdSimEmprestimo");

                    b.ToTable("Emprestimos", (string)null);
                });

            modelBuilder.Entity("Lancamento", b =>
                {
                    b.Property<int>("IdLancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLancamento"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoLancamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdProjecao")
                        .HasColumnType("int");

                    b.Property<int?>("IdSimEmprestimo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ObservacaoLancamento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("idRecorrente")
                        .HasColumnType("int");

                    b.HasKey("IdLancamento");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Lancamentos", (string)null);
                });

            modelBuilder.Entity("ProjetoMidasAPI.Models.Projecao", b =>
                {
                    b.Property<int>("IdProjecao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProjecao"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProjecao");

                    b.ToTable("Projecoes", (string)null);
                });

            modelBuilder.Entity("Recorrencia", b =>
                {
                    b.Property<int>("idRecorrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRecorrente"));

                    b.Property<int?>("IdProjecao")
                        .HasColumnType("int");

                    b.Property<int?>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<int>("TipoRecorrenciaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("dsRecorrente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("momentoCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("obRecorrente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("qtdeRecorrente")
                        .HasColumnType("int");

                    b.HasKey("idRecorrente");

                    b.HasIndex("TipoRecorrenciaId");

                    b.ToTable("Recorrencias", (string)null);
                });

            modelBuilder.Entity("Responsavel", b =>
                {
                    b.Property<int>("IdResponsavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResponsavel"));

                    b.Property<string>("emailResponsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("sobrenomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("telefoneResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdResponsavel");

                    b.ToTable("Responsaveis", (string)null);

                    b.HasData(
                        new
                        {
                            IdResponsavel = 1,
                            emailResponsavel = "joao.silva@teste.com",
                            nomeResponsavel = "João",
                            sobrenomeResponsavel = "Silva",
                            telefoneResponsavel = "987654321"
                        });
                });

            modelBuilder.Entity("TipoRecorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PadraoSistema")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TipoRecorrencias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Mensal",
                            PadraoSistema = true
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Semanal",
                            PadraoSistema = true
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Anual",
                            PadraoSistema = true
                        });
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Visitante");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("emailUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sobrenome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            IdEmpresa = 0,
                            PasswordHash = new byte[] { 151, 41, 79, 235, 246, 177, 138, 132, 252, 63, 235, 251, 141, 1, 198, 167, 0, 62, 75, 223, 53, 174, 152, 79, 184, 243, 8, 17, 64, 161, 247, 79, 33, 119, 235, 251, 239, 35, 196, 41, 18, 24, 18, 164, 8, 190, 1, 252, 167, 206, 208, 74, 27, 242, 38, 38, 68, 113, 171, 114, 115, 5, 153, 202 },
                            PasswordSalt = new byte[] { 144, 173, 226, 156, 110, 54, 66, 113, 62, 49, 57, 33, 81, 34, 104, 74, 69, 226, 11, 179, 187, 159, 208, 217, 215, 126, 211, 163, 185, 224, 219, 101, 65, 3, 18, 104, 220, 246, 241, 155, 167, 226, 114, 240, 51, 148, 131, 248, 168, 22, 25, 76, 5, 176, 44, 178, 188, 169, 75, 97, 97, 34, 53, 97, 23, 39, 168, 186, 69, 19, 211, 1, 202, 133, 48, 105, 175, 129, 47, 21, 5, 156, 53, 74, 73, 93, 131, 36, 43, 88, 237, 22, 111, 138, 130, 154, 248, 45, 107, 112, 154, 80, 20, 104, 111, 81, 237, 45, 84, 212, 121, 239, 212, 238, 73, 162, 76, 192, 71, 56, 121, 157, 217, 67, 149, 192, 40, 121 },
                            Perfil = "Administrador",
                            TipoUsuario = 7,
                            emailUsuario = "",
                            nome = "",
                            nomeUsuario = "Admin",
                            sobrenome = "",
                            telefone = ""
                        });
                });

            modelBuilder.Entity("Lancamento", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Lancamentos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Recorrencia", b =>
                {
                    b.HasOne("TipoRecorrencia", "TipoRecorrencia")
                        .WithMany()
                        .HasForeignKey("TipoRecorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoRecorrencia");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
