// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoMidasAPI.Data;

#nullable disable

namespace ProjetoMidasAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112023622_MigracaoUsuario")]
    partial class MigracaoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("cnpjEmpresa")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("emailEmpresa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("idResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("nomeFantasia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("razaoSocial")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("telefoneEmp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresas", (string)null);

                    b.HasData(
                        new
                        {
                            IdEmpresa = 1,
                            cnpjEmpresa = "12345678901234",
                            emailEmpresa = "empresa@teste.com",
                            idResponsavel = 1,
                            nomeFantasia = "Teste",
                            razaoSocial = "Empresa Teste",
                            telefoneEmp = "123456789"
                        });
                });

            modelBuilder.Entity("Emprestimo", b =>
                {
                    b.Property<int>("IdSimEmprestimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSimEmprestimo"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacaoSE")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IOFemprestimo")
                        .HasColumnType("decimal(5,4)");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<string>("descricaoEmprestimo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("despesasEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("nomeEmprestimo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("parcelasEmprestimo")
                        .HasColumnType("int");

                    b.Property<string>("provedorEmprestimo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tarifasEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorEmprestimo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valorParcelas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdSimEmprestimo");

                    b.ToTable("Emprestimos", (string)null);
                });

            modelBuilder.Entity("Lancamento", b =>
                {
                    b.Property<int>("IdLancamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLancamento"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoLancamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdProjecao")
                        .HasColumnType("int");

                    b.Property<int?>("IdSimEmprestimo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ObservacaoLancamento")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("idRecorrente")
                        .HasColumnType("int");

                    b.HasKey("IdLancamento");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Lancamentos", (string)null);
                });

            modelBuilder.Entity("ProjetoMidasAPI.Models.Projecao", b =>
                {
                    b.Property<int>("IdProjecao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProjecao"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProjecao");

                    b.ToTable("Projecoes", (string)null);
                });

            modelBuilder.Entity("Recorrencia", b =>
                {
                    b.Property<int>("idRecorrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idRecorrente"));

                    b.Property<int?>("IdProjecao")
                        .HasColumnType("int");

                    b.Property<int?>("TipoLancamento")
                        .HasColumnType("int");

                    b.Property<int>("TipoRecorrenciaId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResponsavel")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("dsRecorrente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("momentoCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("obRecorrente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("qtdeRecorrente")
                        .HasColumnType("int");

                    b.HasKey("idRecorrente");

                    b.HasIndex("TipoRecorrenciaId");

                    b.ToTable("Recorrencias", (string)null);
                });

            modelBuilder.Entity("Responsavel", b =>
                {
                    b.Property<int>("IdResponsavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResponsavel"));

                    b.Property<string>("emailResponsavel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("sobrenomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("telefoneResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdResponsavel");

                    b.ToTable("Responsaveis", (string)null);

                    b.HasData(
                        new
                        {
                            IdResponsavel = 1,
                            emailResponsavel = "joao.silva@teste.com",
                            nomeResponsavel = "João",
                            sobrenomeResponsavel = "Silva",
                            telefoneResponsavel = "987654321"
                        });
                });

            modelBuilder.Entity("TipoRecorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PadraoSistema")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TipoRecorrencias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Mensal",
                            PadraoSistema = true
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Semanal",
                            PadraoSistema = true
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Anual",
                            PadraoSistema = true
                        });
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Visitante");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("emailUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("sobrenome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            IdEmpresa = 0,
                            PasswordHash = new byte[] { 69, 168, 91, 91, 195, 220, 168, 215, 187, 218, 234, 145, 250, 172, 186, 39, 18, 164, 107, 250, 133, 163, 221, 73, 28, 14, 119, 4, 133, 54, 147, 235, 49, 184, 88, 79, 6, 230, 11, 84, 93, 126, 150, 94, 203, 8, 187, 192, 112, 190, 181, 95, 33, 208, 155, 0, 121, 91, 39, 20, 140, 110, 177, 190 },
                            PasswordSalt = new byte[] { 156, 150, 67, 155, 242, 25, 80, 39, 65, 156, 162, 85, 109, 108, 192, 228, 74, 30, 229, 27, 86, 14, 220, 156, 197, 29, 241, 137, 125, 26, 0, 73, 223, 147, 35, 163, 221, 245, 138, 150, 0, 189, 63, 86, 8, 191, 4, 86, 214, 136, 190, 214, 45, 2, 153, 73, 248, 46, 97, 9, 147, 106, 1, 193, 245, 123, 55, 114, 141, 117, 23, 84, 192, 189, 6, 142, 101, 34, 43, 126, 246, 183, 102, 68, 12, 124, 201, 247, 23, 230, 157, 32, 49, 246, 93, 83, 234, 111, 4, 186, 47, 40, 205, 110, 1, 215, 66, 128, 64, 110, 209, 118, 167, 228, 178, 36, 65, 53, 199, 152, 160, 99, 168, 208, 190, 54, 109, 195 },
                            Perfil = "Administrador",
                            TipoUsuario = 7,
                            emailUsuario = "",
                            nome = "",
                            nomeUsuario = "Admin",
                            sobrenome = "",
                            telefone = ""
                        });
                });

            modelBuilder.Entity("Lancamento", b =>
                {
                    b.HasOne("Usuario", "Usuario")
                        .WithMany("Lancamentos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Recorrencia", b =>
                {
                    b.HasOne("TipoRecorrencia", "TipoRecorrencia")
                        .WithMany()
                        .HasForeignKey("TipoRecorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoRecorrencia");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
